



all_page_posible_props = [
"auto_scroll",
"bgcolor",
"client_ip",
"client_user_agent",
"horizontal_alignment",
"padding",
"pwa",
"route",
"rtl",
"scroll",
"spacing",
"title",
"vertical_alignment",
"web",
"window_always_on_top",
"window_bgcolor",
"window_focused",
"window_frameless",
"window_full_screen",
"window_height",
"window_left",
"window_maximizable",
"window_maximized",
"window_max_height",
"window_max_width",
"window_minimizable",
"window_minimized",
"window_min_height",
"window_min_width",
"window_movable",
"window_opacity",
"window_resizable",
"window_title_bar_hidden",
"window_title_bar_buttons_hidden",
"window_top",
"window_prevent_close",
"window_skip_task_bar",
"window_visible",
"window_width"
]